# Generated by Django 4.2.23 on 2025-08-24 04:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_summary",
                    models.TextField(help_text="해결 접근/전략/진전 요약 (2~4문장)"),
                ),
                (
                    "highlights",
                    models.TextField(help_text="특징적 시도·반복 난점·개선 포인트 (불릿 허용)"),
                ),
                ("recommendations", models.TextField(help_text="즉시 적용 가능한 권고 (불릿 허용)")),
                (
                    "preview",
                    models.CharField(help_text="리스트/알림용 짧은 미리보기", max_length=160),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context_appropriateness", models.IntegerField()),
                (
                    "context_appropriateness_reason",
                    models.TextField(blank=True, null=True),
                ),
                ("grammer_appropriateness", models.IntegerField()),
                (
                    "grammer_appropriateness_reason",
                    models.TextField(blank=True, null=True),
                ),
                ("vocabulary_appropriateness", models.IntegerField()),
                (
                    "vocabulary_appropriateness_reason",
                    models.TextField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("self_id", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("context", "Context"),
                            ("grammar", "Grammar"),
                            ("vocabulary", "Vocabulary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="ai_app.description",
                    ),
                ),
            ],
        ),
    ]
