# Generated by Django 4.2.23 on 2025-08-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat_app", "0001_initial"),
        ("ai_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description",
                to="chat_app.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="conversationreport",
            name="chat_session",
            field=models.ForeignKey(
                blank=True,
                help_text="보고서가 생성된 현재 채팅 세션(옵션)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="chat_app.chatroom",
            ),
        ),
    ]
