# Generated by Django 4.2.23 on 2025-08-24 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationreport",
            name="user",
            field=models.ForeignKey(
                help_text="보고서 대상 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
