# Generated by Django 4.2.23 on 2025-08-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0002_initial"),
        ("ai_app", "0004_chatsession_message_citation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description",
                to="chat_app.chatmessage",
            ),
        ),
    ]
